name: Power BI Refresh

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python refresh.py
